# Note: this docker-compose file is used for building staging/production images on GitHub Actions.
version: '3.8'

# Define common behavior of web
x-web:
  &default-web
  image: erica_api:latest
  build:
    context: .
    target: erica
    args:
      bucket_name: ${ERICA_BUCKET_NAME}
      access_key_id: ${ACCESS_KEY_ID}
      access_key: ${ACCESS_KEY}
      endpoint_url: ${ENDPOINT_URL}
      elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
      elster_hersteller_id: ${ELSTER_HERSTELLER_ID}
  expose:
    - 8000

# Define common behavior of cron
x-cron:
  &default-cron
  image: erica_cron:latest
  build:
    context: .
    target: cron
    args:
      bucket_name: ${ERICA_BUCKET_NAME}
      access_key_id: ${ACCESS_KEY_ID}
      access_key: ${ACCESS_KEY}
      endpoint_url: ${ENDPOINT_URL}
      elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
      elster_hersteller_id: ${ELSTER_HERSTELLER_ID}

services:
  # Web latest
  web_latest:
    *default-web

  # Web github run
  web_github_run:
    << : *default-web
    image: erica_api:${DOCKER_TAG}

  # Cron latest
  cron_latest:
    *default-cron

  # Cron github run
  cron_github_run:
    << : *default-cron
    image: erica_cron:${DOCKER_TAG}
