# Note: this docker-compose file is used for building staging/production images on GitHub Actions.
version: '3.8'

services:
  web:
    image: erica_api:${DOCKER_TAG:-latest}
    build:
      context: .
      target: erica
      args:
        bucket_name: ${ERICA_BUCKET_NAME}
        access_key_id: ${ACCESS_KEY_ID}
        access_key: ${ACCESS_KEY}
        endpoint_url: ${ENDPOINT_URL}
        elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
        elster_hersteller_id: ${ELSTER_HERSTELLER_ID}
    expose:
      - 8000

  cron:
    image: erica_cron:${DOCKER_TAG:-latest}
    build:
      context: .
      target: cron
      args:
        bucket_name: ${ERICA_BUCKET_NAME}
        access_key_id: ${ACCESS_KEY_ID}
        access_key: ${ACCESS_KEY}
        endpoint_url: ${ENDPOINT_URL}
        elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
        elster_hersteller_id: ${ELSTER_HERSTELLER_ID}
