version: '3.8'
services:
  redis:
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
