# Note: this docker-compose file is used for building staging/production images on GitHub Actions.
version: '3.8'

# Define common behavior of main
x-main:
  &default-main
  image: ${DOCKER_REGISTRY}/erica_main:latest
  build:
    context: .
    target: erica
    args:
      bucket_name: ${ERICA_BUCKET_NAME}
      access_key_id: ${ACCESS_KEY_ID}
      access_key: ${ACCESS_KEY}
      endpoint_url: ${ENDPOINT_URL}
      elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
      elster_hersteller_id: ${ELSTER_HERSTELLER_ID}
  expose:
    - 8000

# Define common behavior of cron
x-cron:
  &default-cron
  image: ${DOCKER_REGISTRY}/erica_cron:latest
  build:
    context: .
    target: cron
    args:
      bucket_name: ${ERICA_BUCKET_NAME}
      access_key_id: ${ACCESS_KEY_ID}
      access_key: ${ACCESS_KEY}
      endpoint_url: ${ENDPOINT_URL}
      elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
      elster_hersteller_id: ${ELSTER_HERSTELLER_ID}

services:
  main_latest:
    *default-main

  main_github_run:
    << : *default-main
    image: ${DOCKER_REGISTRY}/erica_main:${DOCKER_TAG}

  cron_latest:
    *default-cron

  cron_github_run:
    << : *default-cron
    image: ${DOCKER_REGISTRY}/erica_cron:${DOCKER_TAG}
