name: Build image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit sha to build'
        required: true
      imageTag:
        description: 'Label for the image'
        required: true

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE: "steuerlotse_erica:${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code at ref
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Build docker image
      env:
        ERICA_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        ELSTER_DATENLIEFERANT: ${{ secrets.ELSTER_DATENLIEFERANT }}
        ELSTER_HERSTELLER_ID: ${{ secrets.ELSTER_HERSTELLER_ID }}
      run: |
        docker build \
          -t "${{ env.IMAGE }}" \
          --build-arg bucket_name="${ERICA_BUCKET_NAME}" \
          --build-arg access_key_id="${ACCESS_KEY_ID}" \
          --build-arg access_key="${ACCESS_KEY}" \
          --build-arg endpoint_url="${ENDPOINT_URL}" \
          --build-arg elster_datenlieferant="${ELSTER_DATENLIEFERANT}" \
          --build-arg elster_hersteller_id="${ELSTER_HERSTELLER_ID}" \
          -f Dockerfile .
        docker image ls
      shell: bash

    - name: Login to container repository
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}

    - name: Push images
      run: |
        docker tag ${{ env.IMAGE }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE }}
        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE }}
      shell: bash
