name: CI/CD Pipeline

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  ERICA_HOST: ${{ secrets.ERICA_HOST_STAGING }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install build requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.build.txt
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-erica-v${{ secrets.CACHE_VERSION }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pipenv install --dev
        shell: bash

      - name: Get Eric binaries
        env:
          ERICA_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        run: |
          pipenv run python scripts/load_eric_binaries.py download-eric-cert-and-binaries

      - name: Update tax office list
        env:
          ERICA_ENV: testing
        run: |
          pipenv run python scripts/create_tax_office_lists.py create

      - name: Lint
        run: |
          pipenv run invoke --echo lint
        shell: bash

      - name: Test
        run: |
          pipenv run invoke --echo test | tee erica-test-report.log
        shell: bash

      - name: Archive test logs
        uses: actions/upload-artifact@v1
        with:
          name: erica-test-report.log
          path: erica-test-report.log

  build-staging:
    needs: [test]

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker images
        env:
          DOCKER_TAG: ${{ github.run_number }}
          ERICA_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          ELSTER_DATENLIEFERANT: ${{ secrets.ELSTER_DATENLIEFERANT }}
          ELSTER_HERSTELLER_ID: ${{ secrets.ELSTER_HERSTELLER_ID }}
        run: |
          docker-compose -f docker-compose.ci.yml build
          docker image ls
        shell: bash

      - name: Login to container repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - name: Push images
        run: |
          for IMAGE in api cron worker; do
            docker tag erica_${IMAGE}:${{ github.run_number }} ${{ env.DOCKER_REGISTRY }}/erica_${IMAGE}:${{ github.run_number }}
            docker tag erica_${IMAGE}:latest ${{ env.DOCKER_REGISTRY }}/erica_${IMAGE}:latest
            docker push ${{ env.DOCKER_REGISTRY }}/erica_${IMAGE} --all-tags
          done
        shell: bash

  deploy-staging:
    needs: [build-staging]

    if: github.event_name == 'push' #&& github.ref == 'refs/heads/main'

    uses: ./.github/workflows/reusable-deploy-syseleven.yml
    with:
      imageTag: ${{ github.run_number }}
      environment: staging
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_STAGING }}
      CERT_PIN: ${{ secrets.CERT_PIN_STAGING }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_STAGING }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_STAGING }}
      KUBECONFIG_B64: ${{ secrets.CI_KUBECONFIG_B64 }}
      METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
      METRICS_WEBHOOK_TOKEN: ${{ secrets.METRICS_WEBHOOK_TOKEN }}

  contract-tests:
    needs: [deploy-staging]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to container repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - name: Pull deploy image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/steuerlotse_deployment
        shell: bash

      - name: Run contract tests v1
        env:
          NAMESPACE: erica-staging
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker run \
          -e DOCKER_REGISTRY='${{ env.DOCKER_REGISTRY }}' \
          -e REGISTRY_PWD='${{ secrets.REGISTRY_PWD }}' \
          -e KUBECONFIG_BASE64='${{ secrets.CI_KUBECONFIG_B64 }}' \
          -e NAMESPACE='${{ env.NAMESPACE }}' \
          -e IMAGE_TAG='${{ env.IMAGE_TAG }}' \
          -e ERICA_TESTING_URL='${{ secrets.ERICA_TESTING_URL_V1 }}' \
          -e TEST_INTEGRATION_TASK='test-integration' \
          ${{ env.DOCKER_REGISTRY }}/steuerlotse_deployment erica-contract-tests
        shell: bash

      - name: Run contract tests v2
        env:
          NAMESPACE: erica-staging
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker run \
          -e DOCKER_REGISTRY='${{ env.DOCKER_REGISTRY }}' \
          -e REGISTRY_PWD='${{ secrets.REGISTRY_PWD }}' \
          -e KUBECONFIG_BASE64='${{ secrets.CI_KUBECONFIG_B64 }}' \
          -e NAMESPACE='${{ env.NAMESPACE }}' \
          -e IMAGE_TAG='${{ env.IMAGE_TAG }}' \
          -e ERICA_TESTING_URL='${{ secrets.ERICA_TESTING_URL_V2 }}' \
          -e TEST_INTEGRATION_TASK='test-integration-queue' \
          ${{ env.DOCKER_REGISTRY }}/steuerlotse_deployment erica-contract-tests
        shell: bash

      - name: Logout of docker container
        run: docker logout ${{ env.DOCKER_REGISTRY }}
