name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag to deploy"
        required: true
      environment:
        description: "Environment to deploy to"
        required: false
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  syseleven-staging:
    if: ${{ github.event.inputs.environment}} == 'staging'
    uses: ./.github/workflows/reusable-deploy-syseleven.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_STAGING }}
      CERT_PIN: ${{ secrets.CERT_PIN_STAGING }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_STAGING }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_STAGING }}
      KUBECONFIG_B64: ${{ secrets.CI_KUBECONFIG_B64 }}

  otc-staging:
    if: ${{ github.event.inputs.environment}} == 'staging'
    uses: ./.github/workflows/reusable-deploy-otc.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_OTC_STAGING }}
      CERT_PIN: ${{ secrets.CERT_PIN_OTC_STAGING }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_OTC_STAGING }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_OTC_STAGING }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_PIPELINE_PASSWORD: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
  
  track-deploy-staging:
    needs: [syseleven-staging, otc-staging]

    runs-on: ubuntu-latest

    steps:
      - name: Report Deployment
        uses: satak/webrequest-action@v1.2.3
        with:
          url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          method: POST
          payload: '{"project": "Erica", "version_identifier": "${{ github.event.inputs.imageTag }}", "environment": "staging", "link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          headers: '{"Authorization": "Token ${{ secrets.METRICS_WEBHOOK_TOKEN }}"}'

  syseleven-production:
    if: ${{ github.event.inputs.environment}} == 'production'
    uses: ./.github/workflows/reusable-deploy-syseleven.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_PRODUCTION }}
      CERT_PIN: ${{ secrets.CERT_PIN_PRODUCTION }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_PRODUCTION }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_PRODUCTION }}
      KUBECONFIG_B64: ${{ secrets.CI_KUBECONFIG_B64 }}

  otc-production:
    if: ${{ github.event.inputs.environment}} == 'production'
    uses: ./.github/workflows/reusable-deploy-otc.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_OTC_PRODUCTION }}
      CERT_PIN: ${{ secrets.CERT_PIN_OTC_PRODUCTION }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_OTC_PRODUCTION }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_OTC_PRODUCTION }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_PIPELINE_PASSWORD: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}

  track-deploy-production:
    needs: [syseleven-production, otc-production]

    runs-on: ubuntu-latest

    steps:
      - name: Report Deployment
        uses: satak/webrequest-action@v1.2.3
        with:
          url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          method: POST
          payload: '{"project": "Erica", "version_identifier": "${{ github.event.inputs.imageTag }}", "environment": "production", "link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          headers: '{"Authorization": "Token ${{ secrets.METRICS_WEBHOOK_TOKEN }}"}'
