name: Production deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag to deploy"
        required: true

jobs:
  deploy-production:
    uses: ./.github/workflows/reusable-deploy-syseleven.yml
    with:
      imageTag: ${{ inputs.imageTag }}
      environment: production
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_PRODUCTION }}
      CERT_PIN: ${{ secrets.CERT_PIN_PRODUCTION }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_PRODUCTION }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_PRODUCTION }}
      KUBECONFIG_B64: ${{ secrets.CI_KUBECONFIG_B64 }}
      METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
      METRICS_WEBHOOK_TOKEN: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
