name: Production deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag to deploy"
        required: true

jobs:

  otc:
    uses: ./.github/workflows/reusable-deploy-otc.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      environment: production
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
      ERICA_SSH_KEY: ${{ secrets.CI_ERICA_SSH_KEY }}
      ERICA_HOST: ${{ secrets.ERICA_HOST_OTC_PRODUCTION }}
      CERT_PIN: ${{ secrets.CERT_PIN_OTC_PRODUCTION }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_OTC_PRODUCTION }}
      ERICA_DATABASE_URL: ${{ secrets.ERICA_DATABASE_URL_OTC_PRODUCTION }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_PIPELINE_PASSWORD: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}

  track-deploy:
    needs: [otc]

    runs-on: ubuntu-latest

    steps:
      - name: Track deploy
        uses: digitalservicebund/github-actions/track-deployment@b51920b9fdeeb0c8721c210853aee955bd7cefc0
        with:
          project: Erica
          environment: staging
          metrics_deployment_webhook_url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          metrics_webhook_token: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
