name: Deploy

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      REGISTRY_USER:
        required: true
      REGISTRY_PWD:
        required: true
      ERICA_HOST:
        required: true
      ERICA_SSH_KEY:
        required: true
      CERT_PIN:
        required: true
      QUEUE_URL:
        required: true
      ERICA_DATABASE_URL:
        required: true
      DEPLOY_KEY:
        required: true
      ARGOCD_SERVER:
        required: true
      ARGOCD_PIPELINE_PASSWORD:
        required: true

env:
  NAMESPACE: erica-${{ inputs.environment }}

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to container repository
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - name: Pull deploy image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/steuerlotse_deployment
        shell: bash

      - name: Deploy to Kubernetes via ArgoCD
        uses: digitalservice4germany/github-actions/argocd-deploy@e5a88da4a7c71de837e1d813ba6d90faf5ca0c83
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.imageTag }}
          deploying_repo: erica
          infra_repo: erica-infra
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          app: erica-${{ inputs.environment }}
          argocd_pipeline_password: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
          argocd_server: ${{ secrets.ARGOCD_SERVER }}

      - name: Deploy to Erica VM
        run: |
          docker run \
          -e DOCKER_REGISTRY='${{ secrets.DOCKER_REGISTRY }}' \
          -e ERICA_SSH_KEY='${{ secrets.ERICA_SSH_KEY }}' \
          -e ERICA_HOST='${{ secrets.ERICA_HOST }}' \
          -e REGISTRY_PWD='${{ secrets.REGISTRY_PWD }}' \
          -e CERT_PIN='${{ secrets.CERT_PIN }}' \
          -e QUEUE_URL='${{ secrets.QUEUE_URL }}' \
          -e ERICA_DATABASE_URL='${{ secrets.ERICA_DATABASE_URL }}' \
          -e IMAGE_TAG='${{ inputs.imageTag }}' \
          ${{ secrets.DOCKER_REGISTRY }}/steuerlotse_deployment deploy-erica-api-to-vm
        shell: bash

      - name: Logout of container registry
        run: docker logout ${{ secrets.DOCKER_REGISTRY }}
